sudo: true

dist: trusty

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libssl-dev 

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t shiny .
      - docker images
      - docker tag shiny $DOCKER_USERNAME/shiny
      - docker push $DOCKER_USERNAME/shiny