sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t r-julia .
      - docker images
      - docker tag r-julia $DOCKER_USERNAME/r-julia
      - docker push $DOCKER_USERNAME/r-julia
