sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t plumber-mount .
      - docker images
      - docker tag plumber-mount $DOCKER_USERNAME/plumber-mount
      - docker push $DOCKER_USERNAME/plumber-mount