sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 60 docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t shiny-verse .
      - docker images
      - docker tag shiny-verse $DOCKER_USERNAME/shiny-verse
      - docker push $DOCKER_USERNAME/shiny-verse
