sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t shinyproxy .
      - docker images
      - docker tag shinyproxy $DOCKER_USERNAME/shinyproxy
      - docker push $DOCKER_USERNAME/shinyproxy