sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 50 docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t full-r .
      - docker images
      - docker tag full-r $DOCKER_USERNAME/full-r
      - docker push $DOCKER_USERNAME/full-r
