sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg GITHUB_PAT=$GITHUB_PAT -t rstudio-preview .
      - docker images
      - docker tag rstudio-preview $DOCKER_USERNAME/rstudio-preview
      - docker push $DOCKER_USERNAME/rstudio-preview
