sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 60 docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t airflow .
      - docker images
      - docker tag airflow $DOCKER_USERNAME/airflow:1.10.3
      - docker push $DOCKER_USERNAME/airflow:1.10.3
