sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg GITHUB_PAT=$GITHUB_ACCESS_TOKEN -t compact-r .
      - docker images
      - docker tag compact-r $DOCKER_USERNAME/compact-r
      - docker push $DOCKER_USERNAME/compact-r
